source 'http://rubygems.org'

gem 'carrierwave',  '0.5.4'
gem 'compass',      '0.11.3'
gem 'devise'
gem 'devise_invitable', :git => 'https://github.com/rdeshpande/devise_invitable.git'
gem 'endicia',          :git => 'https://github.com/rdeshpande/endicia.git'
gem 'exception_notification', :require => 'exception_notifier'
gem 'impressionist'
gem 'sass',         '3.1.3'
gem 'haml',         '3.1.2'
gem 'mailman'
gem 'daemons'
gem 'fastercsv'
gem 'gmail'#, :git => "http://github.com/rdeshpande/gmail.git"
gem 'haml-rails',   '0.3.4'
gem 'state_machine'
gem 'high_voltage'
gem 'activemerchant', '1.18.1'
gem 'jammit',       '0.6.0'
gem 'jquery-rails', '0.2.7'
gem 'meta_search'
gem 'meta_where'
gem 'mini_magick'
gem 'omniauth',     '1.1.0'
gem 'omniauth-facebook'
gem 'therubyracer'
gem 'barista'
gem 'pg',           '0.11.0'
gem 'rails',        '3.0.9'
gem 'rake',         '0.8.7'
gem 'kaminari'
gem 'rdiscount',    '1.6.8'
gem 'simple_form',  '1.4.1'
gem 'rmagick'
gem 'simple_enum', :git => "https://github.com/lwe/simple_enum.git"
gem 'rest-client',  '1.6.3'
gem 'to_csv', :git => 'https://github.com/standardtoaster/to_csv.git'
gem 'gibbon'
gem 'koala'
gem 'tlsmail'
gem 'whenever'

group :development, :test do
  #gem 'sqlite3',        '1.3.3'
  gem 'hpricot',        '0.8.4' # for html2haml
  gem 'ruby_parser',    '2.0.6'
  gem 'annotate',       '2.4.0', :require => false
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'capistrano_colors'
  gem 'awesome_print'
  gem 'silent-postgres', '0.0.8'
end

group :test do
  gem 'spork'
  gem 'autotest',         '4.4.6'
  gem 'email_spec',       '1.2.1'
  gem 'cucumber-rails'
  gem 'capybara',         '1.0.0'
  gem 'rspec',            '2.6.0'
  gem 'rspec-rails',      '2.6.1'
  gem 'factory_girl_rails', :git => "git://github.com/thoughtbot/factory_girl_rails"
  gem 'database_cleaner', '0.6.6'
  gem 'launchy',          '2.0.5'
end
