embed_assets: off

javascripts:
  defaults:
    - public/javascripts/vendor/jquery-1.6.2.js

    # for multi file upload
    - public/javascripts/vendor/tmpl.min.js
    - public/javascripts/vendor/load-image.min.js
    - public/javascripts/vendor/jquery-ui.js
    - public/javascripts/vendor/jquery.iframe-transport.js
    - public/javascripts/vendor/jquery.fileupload.js
    - public/javascripts/vendor/jquery.fileupload-ui.js

    - public/javascripts/vendor/jquery.infinitescroll.min.js
    - public/javascripts/vendor/jquery.backstretch.js
    - public/javascripts/vendor/jquery.endless-scroll.js
    - public/javascripts/vendor/jquery.easing.1.3.js
    - public/javascripts/vendor/jquery.stickysidebar.js
    - public/javascripts/vendor/jquery.cycle.all.latest.js
    - public/javascripts/vendor/jquery.multiselect.js
    - public/javascripts/vendor/facebox/facebox.js
    - public/javascripts/vendor/easyzoom.js
    - public/javascripts/vendor/jquery.masonry.min.js
    - public/javascripts/vendor/laktek-color-picker/jquery.colorPicker.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
  admin:
    - public/javascripts/vendor/jquery-1.6.2.js
    - public/javascripts/vendor/facebox/facebox.js
    - public/javascripts/vendor/jquery.backstretch.js
    - public/javascripts/vendor/laktek-color-picker/jquery.colorPicker.js
    - public/javascripts/vendor/jquery.autocomplete.js
    - public/javascripts/vendor/nicEdit/nicEdit.js
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  screen:
    - public/javascripts/vendor/laktek-color-picker/colorPicker.css
    - public/javascripts/vendor/facebox/facebox.css
    - public/stylesheets/jquery-ui.css
    - public/stylesheets/jquery.multiselect.css
    - public/stylesheets/jquery.fileupload-ui.css
    - public/stylesheets/compiled/screen.css
  print:
    - public/stylesheets/compiled/print.css
  ie:
    - public/stylesheets/compiled/ie.css
  admin:
    - public/javascripts/vendor/laktek-color-picker/colorPicker.css
    - public/stylesheets/compiled/screen.css
    - public/javascripts/vendor/facebox/facebox.css
    - public/javascripts/vendor/jquery.autocomplete.css
    - public/stylesheets/compiled/admin.css
  admin_print:
