shoes:
  - "5, 35"
  - "5.5, 35.5"
  - "6, 36"
  - "6.5, 36.5"
  - "7, 37"
  - "7.5, 37.5"
  - "8, 38"
  - "8.5, 38.5"
  - "9, 39"
  - "9.5, 39.5"
  - "10, 40"
  - "10.4, 40.5"
  - "11, 41"
  - "11.5, 41.5"
  - "12, 42"

accessories:
  - 'n/a'

bags:
  - 'n/a'

default:
  - "One size"
  - "XS, 0"
  - "S, 2"
  - "S, 4"
  - "M, 6"
  - "M, 8"
  - "L, 10"
  - "L, 12"
  - "XL, 14"

jeans:
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
